Fix `stylelint-config-recommended-less` failures due to pnpm workspace (#37)
* Fix `stylelint-config-recommended-less` failures due to pnpm workspace

* use overrides

* fix

* add feedback

* add feedback

* wip

* wip

* wip

* wip

* wip

* restore other tests

* readme

* fix

* Update data/ecosystem.yml

Co-authored-by: Masafumi Koba <473530+ybiquitous@users.noreply.github.com>

* update-workflows

---------

Co-authored-by: Masafumi Koba <473530+ybiquitous@users.noreply.github.com>

diff --git a/.github/workflows/test-package.yml b/.github/workflows/test-package.yml
--- a/.github/workflows/test-package.yml
+++ b/.github/workflows/test-package.yml
@@ -11,14 +11,28 @@ on:
         type: string
         description: The Stylelint version to test
         required: true
-      test-command:
+      stylelint-version-override:
         type: string
-        description: The test command to run
-        default: 'npm test'
+        description: The Stylelint version override
+      set-overrides-command:
+        type: string
+        description: The command to set dependency overrides
       install-command:
         type: string
         description: The install command to run
         default: 'npm install --no-audit'
+      list-installed-versions-command:
+        type: string
+        description: The list dependencies command to run
+        default: 'npm list stylelint'
+      build-command:
+        type: string
+        description: The build command to run
+        default: 'npm run build --if-present'
+      test-command:
+        type: string
+        description: The test command to run
+        default: 'npm test'
 
 jobs:
   test:
@@ -67,8 +81,20 @@ jobs:
           npm install --global yarn
           echo "yarn: $(yarn --version)"
 
+      - name: Set dependency overrides
+        env:
+          SET_OVERRIDES_COMMAND: ${{ inputs.set-overrides-command }}
+          STYLELINT_VERSION_OVERRIDE: ${{ inputs.stylelint-version-override }}
+        if: ${{ inputs.set-overrides-command }}
+        run: |
+          if ! eval "$SET_OVERRIDES_COMMAND=$STYLELINT_VERSION_OVERRIDE"; then
+            echo "::error ::Setting dependency overrides failed."
+            exit 1
+          fi
+
+          npm pkg get;
+
       - name: Install dependencies
-        id: install-dependencies
         working-directory: ${{ steps.repo-info.outputs.directory }}
         env:
           PACKAGE_URL: ${{ steps.repo-info.outputs.url }}
@@ -80,8 +106,8 @@ jobs:
           fi
 
       - name: Install Stylelint ${{ inputs.stylelint-version }}
-        id: install-stylelint
         working-directory: ${{ steps.repo-info.outputs.directory }}
+        if: ${{ ! inputs.set-overrides-command }}
         env:
           STYLELINT_VERSION: ${{ inputs.stylelint-version }}
           PACKAGE_URL: ${{ steps.repo-info.outputs.url }}
@@ -91,19 +117,29 @@ jobs:
             exit 1
           fi
 
-      - name: Run build
-        id: build
+      - name: List installed Stylelint versions
         working-directory: ${{ steps.repo-info.outputs.directory }}
         env:
           PACKAGE_URL: ${{ steps.repo-info.outputs.url }}
+          LIST_INSTALLED_VERSIONS_COMMAND: ${{ inputs.list-installed-versions-command }}
         run: |
-          if ! npm run build --if-present; then
+          if ! eval "$LIST_INSTALLED_VERSIONS_COMMAND"; then
+            echo "::error ::Listing dependencies failed."
+            # `npm list` has a non-zero exit code when overriding dependencies
+          fi
+
+      - name: Run build
+        working-directory: ${{ steps.repo-info.outputs.directory }}
+        env:
+          PACKAGE_URL: ${{ steps.repo-info.outputs.url }}
+          BUILD_COMMAND: ${{ inputs.build-command }}
+        run: |
+          if ! eval "$BUILD_COMMAND"; then
             echo "::error ::The build failed. Visit ${PACKAGE_URL}"
             exit 1
           fi
 
       - name: Run test
-        id: test
         working-directory: ${{ steps.repo-info.outputs.directory }}
         env:
           PACKAGE_URL: ${{ steps.repo-info.outputs.url }}
